name: ESP32-Build
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - working-directory: /home/runner/work/ESP32-Camera-micropython/ESP32-Camera-micropython/esp-idf
        run: |
             ls
             ./install.sh
             . ./export.sh
             cd /home/runner/work/ESP32-Camera-micropython/ESP32-Camera-micropython/micropython/ports/esp32
             make
      - uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
                /home/runner/work/ESP32-Camera-micropython/ESP32-Camera-micropython/micropython/ports/esp32/build-GENERIC_CAM/firmware.bin
